- become: yes
  hosts: all
  name: apache-install

  tasks:
    - name: Create Filesystem
      filesystem:
        fstype: ext4
        dev: /dev/xvdb

    - name: Mount Filesystem
      mount:
        path: /var/www/html
        src: /dev/xvdb
        fstype: ext4
        state: present

    - name: install apache & amazon cloudwatch
      yum:
        name: httpd, amazon-cloudwatch-agent, git
        state: present
        update_cache: true

    - name: Get directory listing
      become: yes
      find:
        paths: /var/www/html
        patterns: '*'
        hidden: yes
      register: directory_content_result
    
    - name: Remove directory content
      become: yes
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ directory_content_result.files }}"

    - name: Sync Web Site
      git:
        repo: 'https://bitbucket.org/dptrealtime/html-web-app.git'
        dest: /var/www/html

    - name: Copy cloudwatch condfig
      copy:
        src: amazon-cloudwatch-agent.json
        dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
      notify:
        - Restart cloudwatch

  handlers:
    - name: Restart cloudwatch
      service:
        name: amazon-cloudwatch-agent
        state: restarted